version: '3.7'

services:
  web:
    build:
      context: ./apache
    ports:
      - 80:80
    networks:
      - ui
    depends_on:
      - app
    hostname: web
    container_name: web
    volumes:
      - html:/usr/local/apache2/htdocs/

  app:
    build: tomcat/
    ports:
      - 8080:8080
      - 9001:9001
    networks:
      - ui
      - db
    depends_on:
      - mongodb
    hostname: app
    container_name: app
#    links:
#    - mongodb:mongodb
    volumes:
    - logs:/usr/local/tomcat/logs/

  mongodb:
    build: mongodb/
    ports:
      - 27017:27017
    networks:
      - db
    hostname: mongodb
    container_name: mongo
    volumes:
      - data:/data/db
      - data:/data/configdb

volumes:
  html:
    driver_opts:
      type: none
      device: /c/Development/work/html
      o: bind
  logs:
    driver_opts:
      type: none
      device: /c/Development/work/logs
      o: bind
  data:
    driver_opts:
      type: none
      device: /c/Development/work/db
      o: bind

networks:
  ui:
    driver: bridge
  db:
    driver: bridge
