version: '3.7'

services:
  web:
    build: apache/
    restart: always
    ports:
      - 80:80
    networks:
      - internal
    depends_on:
      - app
    #hostname: web
    container_name: web
    volumes:
      - html:/usr/local/apache2/htdocs/

  app:
    build: tomcat/
    restart: always
    ports:
      - 8080:8080
      - 9001:9001
    networks:
      - internal
    depends_on:
      - mongo
    #hostname: app
    container_name: app
#    links:
#    - mongodb:mongodb
    volumes:
    - logs:/usr/local/tomcat/logs/

  mongo:
    build: mongodb/
    restart: always
    ports:
      - 27017:27017
    networks:
      - internal
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    #hostname: mongo
    container_name: mongo
    volumes:
      - data:/data/backup

volumes:
  html:
    driver_opts:
      type: none
      device: ${DEV_WORK}/html
      o: bind
  logs:
    driver_opts:
      type: none
      device: ${DEV_WORK}/logs
      o: bind
  data:
    driver_opts:
      type: none
      device: ${DEV_WORK}/db
      o: bind

networks:
  internal:
#  ui:
#    driver: bridge
#  db:
#    driver: bridge
