FROM httpd:alpine
LABEL maintainer="Curtis White <curtisawhite77@gmail.com>"
LABEL description="Image containing Apache Web Server on port 80"

# Make port 80 available to the world outside this container
EXPOSE 80


