FROM httpd:alpine
LABEL maintainer="Curtis White <curtisawhite77@gmail.com>"
LABEL description="Image containing Apache that links to the tomcat container"

# Make port 80 available to the world outside this container
EXPOSE 80

